server:
  port: 8081

spring:
  application:
    name: miro-backend-service
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

#jwt:
#  secretKey: ${jwt.secretKey}  # This allows overriding the secretKey via the profile